### ISSUE TITLE
Add fuzzy finder ui

### ISSUE THREAD

**Issue by prabirshrestha** [skanehira/vsession#2]
I have lot of sessions and would like to use fuzzy finder ui. I don't use fzf.vim.

You can embed [quickpick.vim](https://github.com/prabirshrestha/quickpick.vim) which is also embedded in vim-lsp. Instructions on embedding can be found at https://github.com/prabirshrestha/quickpick.vim#embedding.

Here is a simple example you can use. https://github.com/prabirshrestha/quickpick-colorschemes.vim

**Comment by prabirshrestha** [comment]
Also would be good to add `vession#list()` function.

If you are interested I can also submit the PR.

**Comment by skanehira** [comment]
@prabirshrestha 
Thank you :)
Would you give me PR?

**Comment by prabirshrestha** [comment]
Sure.

* I have been thinking of is instead of using. `g:vsession_use_fzf` we can change it to `g:vsession_load_ui = 'fzf|quickpick|inputlist|popup'`. Or just have quickpick and don't worry about anything else.
* Also might want to support `load(sessionname)` and `list()` so anyone can make the ui.
